### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by IoApo**
Added Greek language translated text strings. (Link follows site at the EN destination as there is no direct match for EL language).

### CODE REVIEW

**Comment by timonf** [comment]
Thanks a lot, again! :) 

You can also provide a Greek link, which contains a lot of neutral information about the EU copyright directive/reform!

**Comment by IoApo** [comment]
Thank you for your quick response! 
There is a blog article/post (in Greek) that summarizes the concequenses of the proposed directive. It seems very nice and well explained, on [https://www.roussos.cc/2019/03/05/copyright-reform/](https://www.roussos.cc/2019/03/05/copyright-reform/). Should I just replace the reference with that?

**Comment by timonf** [comment]
Do you think Greek people would prefer this? Then: yes! :) Looks good to me!

**Comment by IoApo** [comment]
> 
> 
> Do you think Greek people would prefer this? Then: yes! :) Looks good to me!

Sure! Indeed I noticed that it was re-bloged on https://openstandards.ellak.gr/2019/03/08/nea-apo-ton-planiti-planet-ellak-gr-copyright-reform/ on the official site of Open Technologies Alliance (GFOSS), a greek non-profit organization where Universities and Research Centers are shareholders and seems they also find this blog post very representative on the issue... 
_(GFOSS is also affiliated with Creative Commons, is a founding member of COMMUNIA, member of the Open Government Partnership Network, Node of the Open Data Institute, member of the Open Budget Initiative, member of the Open Policy Network, Associate Organisation of FSFE, Associate Member of Eclipse Foundation, Associate Organization of OW2 Consortium, among others)_.

**Comment by timonf** [comment]
@IoApo 

→ Should I use the new link? (provided by openstandards.ellak.gr)
→ I am playing around with sizes a little bit at the moment. Do you think this is okay?
→ Is the `,` there okay? I think it's an English thing, to add something like ", too" at the end.

image

**Comment by IoApo** [comment]
> 
> 
> @IoApo
> 
> → Should I use the new link? (provided by openstandards.ellak.gr)
> → I am playing around with sizes a little bit at the moment. Do you think this is okay?
> → Is the `,` there okay? I think it's an English thing, to add something like ", too" at the end.
> 

Thank you again! I'll try to answer accordingly:  

→ The new link (from openstandards.ellak.gr) is just a re-blog/re-post of the previous (from roussos.cc) which is the original writer/person. Feel free to choose whatever seems better!

→ Size is great, no problem with that! Looks awesome! 

→ In my humble opinion, the "too" is not very common in natural flow of spoken language here. The use of word "επίσης", has a similarity to "also" / "in addition", and goes after the verb in most times. So, if it was a 3-part string values, I may suggesτ to go like that: 
1. "`Αυτή η σελίδα θα επηρεαστεί επίσης από την`"
2. "`Οδηγία της ΕΕ για τα δικαιώματα πνευματικής ιδιοκτησίας`"
3. ""

so, in that case, ommiting the  `,`  comma (better maybe: by inserting it in part-3 but as not a "hard-coded" required option), then, in Greek we can stay only on parts as 1+2+"" and the questionmark afterwards, injecting the "επίσης", in the part-1 that seems more natural, I guess.. 

Alternatively, there could be an emphasis in another way too, by following a slightly different approach: 
1. "`Και αυτή η σελίδα θα επηρεαστεί από την`"
2. "`Οδηγία της ΕΕ για τα δικαιώματα πνευματικής ιδιοκτησίας`"
3. ""

Here, we add "Και" (="and") at the start of the phrase. This is not strictly grammatically correct, but it is quite often applied to literature (poems, etc) as it adds an emphasis to the meaning and is probably accepted in this case. Here there are more similarities with "too" which is placed at the end of the sentense (in English). Either way, the part-1 value can offer that kind of freedom. 
Part-3 value is what makes it a bit... stressful :)

**Comment by timonf** [comment]
Okay… I try both approaches, and compare the optical results of both variants. Empty third string is fine to me!

**Pull request merged**
